version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"  # Location of pom.xml
    schedule:
      interval: "weekly"  # Can be daily, weekly, or monthly
    open-pull-requests-limit: 5
